-- Semeia os 21 processos e as 23 ligações do mapa de processos da casa em
-- `StaffProcess` e `StaffProcessEdge`.
--
-- O QUE SEMEIA
--   Os 21 processos (código, nome, descrição, domínio, nível, tipo, dono,
--   revisado em, tags) e as 23 ligações (de → para, rótulo) de
--   packages/provisioning/src/processos-nebuloz.ts (`PROCESSOS_NEBULOZ`,
--   `LIGACOES_NEBULOZ`), mesmo código e mesmos pares desse arquivo. Gerado a
--   partir dele — se a lista mudar lá, gere este arquivo de novo.
--
-- SÓ CRIA
--   Todo INSERT tem `ON CONFLICT ... DO NOTHING`: rodar de novo, ou rodar
--   depois de um processo/ligação já ter sido editado pela tela, não
--   sobrescreve nada.
--
-- ORDEM DE DEPLOY
--   1. O deploy da Vercel aplica a migration `20260909000000_mapa_de_processos`
--      (cria `StaffProcess` e `StaffProcessEdge`, com RLS — nada disso
--      depende deste script).
--   2. Rode este arquivo no SQL Editor do Supabase.
--   3. Confira o SELECT final: deve devolver `21 | 23`.
--   Até o passo 2 rodar, a tela `/ferramentas/processos` abre vazia com o
--   estado de "nenhum processo" — não quebra.

BEGIN;

INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz01','system','PZ-01','Funil de leads','Lead → descoberta → avaliação → proposta. Saída sempre registrada.','COMERCIAL',2,'CORE','marina','2026-08-28'::timestamp,ARRAY['lead','estágio','cac','porta de entrada']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz02','system','PZ-02','Geração de proposta','Escopo → preço de tabela → desconto → envio ao decisor.','COMERCIAL',3,'CORE','marina','2026-08-20'::timestamp,ARRAY['preço','acv','assentos','serviço']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz03','system','PZ-03','Simulação de capacidade','Se eu ganhar esta proposta, quebro alguém? Roda antes do envio.','DELIVERY',2,'APOIO','artur','2026-08-14'::timestamp,ARRAY['alocação','horas','kickoff','quebra']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz04','system','PZ-04','Kickoff de engajamento','Contrato assinado → time alocado → primeira semana.','DELIVERY',3,'CORE','tiago','2026-07-02'::timestamp,ARRAY['onboarding','time','escopo','cliente']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz05','system','PZ-05','Gate de fase (Scaffold)','Critérios atendidos ou override nomeado. Nunca fecha em silêncio.','DELIVERY',2,'CORE','artur','2026-08-25'::timestamp,ARRAY['assess','pilot','scale','embed','override','critério']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz06','system','PZ-06','Encerramento de engajamento','Entrega final, handover ao cliente, post-mortem interno.','DELIVERY',3,'CORE','tiago','2026-06-11'::timestamp,ARRAY['handover','lições','renovação']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz07','system','PZ-07','Intake de caso de IA','Caso submetido → triagem → classe de dado → decisão.','GOVERNANCA',3,'CORE','sofia','2026-08-04'::timestamp,ARRAY['caso','triagem','classe de dado','risco']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz08','system','PZ-08','Revisão de risco e vendor','Matriz de risco por classe de dado; cláusulas de contrato.','GOVERNANCA',2,'CORE','sofia','2026-07-30'::timestamp,ARRAY['vendor','cláusula','dpa','matriz']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz09','system','PZ-09','Publicação de política','Rascunho → aprovação → publicação → ciência dos times.','GOVERNANCA',1,'APOIO','sofia','2026-05-18'::timestamp,ARRAY['política','versão','ciência','onboarding']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz10','system','PZ-10','Provisionamento de tenant','Proposta ganha → tenant criado → módulos contratados → owner convidado.','PLATAFORMA',3,'CORE','marina','2026-08-22'::timestamp,ARRAY['tenant','módulo','owner','convite']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz11','system','PZ-11','Suspensão e deleção','Read-only → full-lock → deleção agendada com aprovação.','PLATAFORMA',2,'APOIO','marina','2026-08-05'::timestamp,ARRAY['read-only','lock','aprovação','retenção']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz12','system','PZ-12','Aprovação de MCP writes','Pedido do cliente → revisão → modo concedido. Hoje é e-mail.','PLATAFORMA',2,'APOIO','marina',NULL,ARRAY['mcp','gateway','writes','aprovação']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz13','system','PZ-13','Curadoria de dataset','Coleta → remoção de PII → licença → pronto para treino.','LAB',3,'CORE','renata','2026-07-20'::timestamp,ARRAY['pii','licença','dataset','revisão']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz14','system','PZ-14','Promoção de modelo','Shadow → canary → GA. Cada degrau exige avaliação e card.','LAB',2,'CORE','renata','2026-07-31'::timestamp,ARRAY['shadow','canary','ga','eval','model card']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz15','system','PZ-15','Baseline assinado','Medido antes do trabalho; assinado pelo dono do processo; emitido no gate.','MEDICAO',2,'CORE','artur','2026-08-15'::timestamp,ARRAY['baseline','assinatura','dono do processo','métrica']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz17','system','PZ-17','Meta e tabela de preço','Define PRICING, pisos de assento e alçada de desconto. Revisado uma vez por ano.','COMERCIAL',1,'CORE','marina','2026-01-10'::timestamp,ARRAY['meta','pricing','tabela','desconto','anual']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz18','system','PZ-18','Método da Escada','Cinco degraus, nesta ordem. Publica templates e critérios que o gate consome.','DELIVERY',1,'CORE','artur','2026-08-05'::timestamp,ARRAY['diagnose','structure','measure','govern','operate','template','fase']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz19','system','PZ-19','Planos e limites por tenant','Define o que cada plano libera: assentos, integrações, MCP, papéis.','PLATAFORMA',1,'CORE','marina','2026-03-03'::timestamp,ARRAY['plano','starter','scale','enterprise','limite','mcp']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz20','system','PZ-20','Roadmap do modelo próprio','Que modelo treinar, para que tenant, com que GPU. Hoje é uma planilha.','LAB',1,'CORE','renata',NULL,ARRAY['roadmap','slm','capacidade','gpu','prioridade']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz21','system','PZ-21','Coleta e mapeamento de métricas','Evento da fonte → métrica → fórmula versionada. Roda a cada sync.','MEDICAO',3,'APOIO','artur','2026-08-20'::timestamp,ARRAY['evento','fonte','fórmula','frescor','conexão']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;
INSERT INTO "StaffProcess" ("id","tenantId","codigo","nome","descricao","dominio","nivel","tipo","donoNome","revisadoEm","tags","atualizadoEm") VALUES ('proc_pz16','system','PZ-16','Decisão de valor','Comitê mensal decide continuar, escalar, pivotar ou encerrar.','MEDICAO',1,'CORE','marina','2026-09-01'::timestamp,ARRAY['comitê','veredito','escalar','encerrar','rationale']::text[],now()) ON CONFLICT ("tenantId","codigo") DO NOTHING;

INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge01','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-01'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-02'),'converte em') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge02','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-02'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-03'),'exige') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge03','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-02'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-10'),'ganha → dispara') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge04','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-10'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-04'),'dispara') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge05','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-04'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-05'),'roda em') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge06','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-05'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-15'),'emite') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge07','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-15'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-16'),'alimenta') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge08','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-05'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-06'),'termina em') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge09','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-07'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-08'),'escala para') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge10','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-08'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-09'),'atualiza') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge11','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-09'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-05'),'condiciona scale') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge12','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-07'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-12'),'classifica') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge13','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-13'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-14'),'alimenta') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge14','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-14'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-08'),'passa por') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge15','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-11'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-06'),'após') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge16','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-16'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-02'),'escalar → nova') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge17','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-17'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-02'),'define tabela de') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge18','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-18'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-05'),'define critérios de') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge19','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-19'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-10'),'parametriza') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge20','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-19'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-12'),'limita') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge21','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-20'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-13'),'prioriza') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge22','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-21'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-15'),'alimenta') ON CONFLICT ("deId","paraId") DO NOTHING;
INSERT INTO "StaffProcessEdge" ("id","tenantId","deId","paraId","rotulo") VALUES ('proc_edge23','system',(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-16'),(SELECT id FROM "StaffProcess" WHERE "tenantId"='system' AND codigo='PZ-17'),'realimenta') ON CONFLICT ("deId","paraId") DO NOTHING;

COMMIT;

SELECT
  (SELECT count(*) FROM "StaffProcess" WHERE "tenantId"='system') AS processos,
  (SELECT count(*) FROM "StaffProcessEdge" WHERE "tenantId"='system') AS ligacoes;
