import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Autogerado a partir de `docs/produto/` — PRD/SRD interno de Cosmos e
 * Back-office, além de trilhas e material de pesquisa. Novo arquivo em
 * `docs/produto/` aparece aqui sem precisar editar este arquivo.
 */
const sidebars: SidebarsConfig = {
  interno: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
