// icons.tsx — cosmos icon set. The handoff shipped custom lucide-style SVG paths;
// we back them with lucide-react (installed) keyed by the same string names the
// kit/shell reference. ponytail: reuse lucide instead of hand-porting ~60 paths.
// Glifos exigidos pelo Charter (charter-base.jsx do handoff) que o set do
// Cosmos ainda não referenciava. Adição pura — nada existente muda de nome.
import {
  Activity,
  AlertTriangle,
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Code,
  Columns3,
  Compass,
  Copy,
  Cpu,
  Crosshair,
  createLucideIcon,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode2,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  Gauge,
  Gavel,
  GitBranch,
  GitCompareArrows,
  GripVertical,
  Handshake,
  Heart,
  History,
  Inbox,
  Key,
  Layers,
  LayoutGrid,
  LineChart,
  Link2,
  List,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  Maximize2,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  PanelLeft,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  Route,
  Ruler,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Shuffle,
  SignalHigh,
  Slash,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  TrendingDown,
  TrendingUp,
  Upload,
  UserCheck,
  Users,
  Wallet,
  Wand2,
  Webhook,
  Workflow,
  X,
  Zap,
} from "lucide-react";
import type { CSSProperties } from "react";

// Glifo do mapa de processos (spec §4): `createLucideIcon` reproduz os traços
// exatos do design (backoffice-process-map.jsx, bloco `Object.assign(ICON_PATHS,
// …)`) com o mesmo comportamento de prop das demais entradas deste arquivo —
// nenhum ícone do lucide-react se pareceria com esse desenho específico.
const Graph = createLucideIcon("Graph", [
  ["circle", { cx: "6", cy: "6", r: "2.5" }],
  ["circle", { cx: "18", cy: "8", r: "2.5" }],
  ["circle", { cx: "9", cy: "18", r: "2.5" }],
  ["circle", { cx: "19", cy: "17", r: "2" }],
  [
    "path",
    { d: "m8.2 7.2 7.4 0.6M7.2 8.3l1.2 7.3M11.4 17.6l5.6-.4M16.3 10.2l2 4.9" },
  ],
]);

const ICONS = {
  search: Search,
  plus: Plus,
  minus: Minus,
  arrowLeft: ArrowLeft,
  inbox: Inbox,
  history: History,
  upload: Upload,
  approve: ShieldCheck,
  fileCode: FileCode2,
  server: Server,
  logout: LogOut,
  handshake: Handshake,
  briefcase: Briefcase,
  heart: Heart,
  chart: LineChart,
  dataset: Database,
  cpu: Cpu,
  ban: Ban,
  userCheck: UserCheck,
  gavel: Gavel,
  slash: Slash,
  arrowRight: ArrowRight,
  grid: LayoutGrid,
  target: Target,
  users: Users,
  barChart: BarChart3,
  flow: Workflow,
  anchor: Anchor,
  plug: Plug,
  settings: Settings,
  webhook: Webhook,
  bot: Bot,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  trend: TrendingUp,
  trending: TrendingUp,
  kanban: Columns3,
  x: X,
  shuffle: Shuffle,
  flask: FlaskConical,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  activity: Activity,
  check: Check,
  clock: Clock,
  dollar: DollarSign,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  gauge: Gauge,
  layers: Layers,
  zap: Zap,
  alert: AlertTriangle,
  calendar: Calendar,
  tag: Tag,
  filter: Filter,
  wand: Wand2,
  panelLeft: PanelLeft,
  more: MoreHorizontal,
  gripVertical: GripVertical,
  externalLink: ExternalLink,
  arrowUpRight: ArrowUpRight,
  paperclip: Paperclip,
  send: Send,
  flag: Flag,
  building: Building2,
  shield: Shield,
  gitBranch: GitBranch,
  star: Star,
  route: Route,
  wallet: Wallet,
  compass: Compass,
  pulse: Activity,
  scale: Scale,
  refresh: RefreshCw,
  award: Award,
  book: BookOpen,
  play: Play,
  pause: Pause,
  puzzle: Puzzle,
  lock: Lock,
  key: Key,
  code: Code,
  message: MessageSquare,
  mail: Mail,
  copy: Copy,
  eye: Eye,
  download: Download,
  maximize: Maximize2,
  fileText: FileText,
  // Glifos exigidos pelo Meridian (meridian-registry.jsx / nebuloz-seams.jsx do
  // handoff). Adição pura — nada existente muda de nome.
  crosshair: Crosshair,
  diff: GitCompareArrows,
  outbound: ExternalLink,
  // Glifos exigidos pelo Signal (signal-data.jsx do handoff). Adição pura —
  // nada existente muda de nome. `signal` usa SignalHigh (barras ascendentes),
  // o glifo mais próximo do path do handoff; `flag2` não entra porque `flag` já
  // cobre o mesmo significado.
  signal: SignalHigh,
  ruler: Ruler,
  database: Database,
  eyeOff: EyeOff,
  edit: Pencil,
  link2: Link2,
  list: List,
  box: Box,
  // Glifo exigido pelo mapa de processos (backoffice-process-map.jsx do
  // handoff). Adição pura — nada existente muda de nome.
  graph: Graph,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = {
  name: IconName | (string & {});
  size?: number;
  strokeWidth?: number;
  style?: CSSProperties;
  className?: string;
};

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.9,
  style,
  className,
}: IconProps) {
  const Cmp = ICONS[name as IconName];
  if (!Cmp) {
    return null;
  }
  return (
    <Cmp
      aria-hidden="true"
      className={className}
      height={size}
      strokeWidth={strokeWidth}
      style={{ display: "block", flexShrink: 0, ...style }}
      width={size}
    />
  );
}
