import type { ProcessoBpmnEntrada } from "@repo/bpmn";

const MAPA = "docs/comercial/mapa-de-processo.md";

export const PZ_02: ProcessoBpmnEntrada = {
  codigo: "PZ-02",
  nome: "Geração de proposta",
  fonte: [
    {
      arquivo: MAPA,
      secao: "§3 Precificação; §4 Proposta; §8 Diagrama de estados",
    },
    {
      arquivo: "docs/comercial/playbook-de-vendas.md",
      secao: "§2 'Está caro' — teto de 15% sem aprovação",
    },
    {
      arquivo: "apps/backoffice/app/actions/approvals.ts",
      secao:
        "despacharAcaoAprovada — aprovado vira ENVIADA, rejeitado volta a RASCUNHO",
    },
  ],
  lacunas: [
    "Não existe ação no back-office que marque proposta ENVIADA como ACEITA ou RECUSADA (mapa §4). O desenho mostra a decisão do cliente porque os estados existem, mas nada a registra.",
    "Sem motivo estruturado de recusa e sem validade/expiração da proposta (mapa §4 e §9).",
    "Proposal.aceitaEm ausente: sem data do aceite, o CAC conta clientes ganhos por aproximação (mapa §9).",
    "Ticket do diagnóstico (SKU de entrada) sem definição — decisão em aberto, não código (mapa §3).",
    "O mapa de processos liga PZ-02 → PZ-03 ('exige' simulação de capacidade antes do envio), mas a fonte escrita do comercial não cita esse passo; não foi desenhado.",
    "RACI de quem monta e de quem aprova está em branco (playbook §4); as raias nomeiam papéis, não pessoas.",
  ],
  pool: "Nebuloz — proposta comercial",
  raias: [
    { id: "Raia_vendedor", nome: "Quem monta a proposta" },
    { id: "Raia_sistema", nome: "Back-office" },
    { id: "Raia_aprovador", nome: "Outro ADMIN (aprovação)" },
    { id: "Raia_cliente", nome: "Cliente (decisor)" },
  ],
  nos: [
    {
      id: "Inicio",
      tipo: "inicio",
      nome: "Lead convertido em proposta (PZ-01)",
      raia: "Raia_vendedor",
      origem: "mapa §2 → §3",
    },
    {
      id: "Retrabalho",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_vendedor",
    },
    {
      id: "MontarEscopo",
      tipo: "tarefaUsuario",
      nome: "Montar escopo: plano, assentos, add-ons, serviços e desconto",
      raia: "Raia_vendedor",
      origem: "mapa §3 Entrada; actions/proposta-escopo.ts",
    },
    {
      id: "Precificar",
      tipo: "tarefaServico",
      nome: "Precificar (precificarProposta): mensal, uma vez, ACV, TCV",
      raia: "Raia_sistema",
      origem: "mapa §3; lib/comercial/precificar.ts",
    },
    {
      id: "Enviar",
      tipo: "tarefaUsuario",
      nome: "Enviar proposta (submitProposalAction)",
      raia: "Raia_vendedor",
      origem: "mapa §4",
    },
    {
      id: "Congelar",
      tipo: "tarefaServico",
      nome: "Congelar total e ACV no envio",
      raia: "Raia_sistema",
      origem: "mapa §4 (totalCentavos e acvCentavos)",
    },
    {
      id: "AcimaDoTeto",
      tipo: "gatewayExclusivo",
      nome: "Desconto acima de 15%?",
      raia: "Raia_sistema",
      origem: "mapa §3; lib/comercial.ts LIMITE_DESCONTO_SEM_APROVACAO",
    },
    {
      id: "AbrirPedido",
      tipo: "tarefaServico",
      nome: "Abrir pedido em PlatformApproval (AGUARDANDO_APROVACAO)",
      raia: "Raia_sistema",
      origem: "mapa §4",
    },
    {
      id: "Decidir",
      tipo: "tarefaUsuario",
      nome: "Decidir o pedido — quem pediu não decide",
      raia: "Raia_aprovador",
      origem: "actions/approvals.ts; PRODUCT.md princípio 2",
    },
    {
      id: "Aprovado",
      tipo: "gatewayExclusivo",
      nome: "Aprovado?",
      raia: "Raia_aprovador",
      origem: "actions/approvals.ts",
    },
    {
      id: "VoltaRascunho",
      tipo: "tarefaServico",
      nome: "Proposta volta a RASCUNHO",
      raia: "Raia_sistema",
      origem: "actions/approvals.ts despacharAcaoAprovada",
    },
    {
      id: "JuntaEnvio",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_sistema",
    },
    {
      id: "MarcarEnviada",
      tipo: "tarefaServico",
      nome: "Status ENVIADA",
      raia: "Raia_sistema",
      origem: "mapa §4",
    },
    {
      id: "ClienteDecide",
      tipo: "tarefaManual",
      nome: "Cliente decide aceite ou recusa",
      raia: "Raia_cliente",
      origem: "mapa §4 Dono",
    },
    {
      id: "Aceitou",
      tipo: "gatewayExclusivo",
      nome: "Aceitou?",
      raia: "Raia_cliente",
      origem: "mapa §4 Saída; §8",
    },
    {
      id: "Aceita",
      tipo: "fim",
      nome: "ACEITA — provisionamento à mão (PZ-10)",
      raia: "Raia_cliente",
      origem: "mapa §6; §8",
    },
    {
      id: "Recusada",
      tipo: "fim",
      nome: "RECUSADA",
      raia: "Raia_cliente",
      origem: "mapa §8",
    },
  ],
  fluxos: [
    { de: "Inicio", para: "Retrabalho" },
    { de: "Retrabalho", para: "MontarEscopo" },
    { de: "MontarEscopo", para: "Precificar" },
    { de: "Precificar", para: "Enviar" },
    { de: "Enviar", para: "Congelar" },
    { de: "Congelar", para: "AcimaDoTeto" },
    { de: "AcimaDoTeto", para: "JuntaEnvio", condicao: "não" },
    { de: "AcimaDoTeto", para: "AbrirPedido", condicao: "sim" },
    { de: "AbrirPedido", para: "Decidir" },
    { de: "Decidir", para: "Aprovado" },
    { de: "Aprovado", para: "JuntaEnvio", condicao: "sim" },
    { de: "Aprovado", para: "VoltaRascunho", condicao: "não" },
    { de: "VoltaRascunho", para: "Retrabalho" },
    { de: "JuntaEnvio", para: "MarcarEnviada" },
    { de: "MarcarEnviada", para: "ClienteDecide" },
    { de: "ClienteDecide", para: "Aceitou" },
    { de: "Aceitou", para: "Aceita", condicao: "sim" },
    { de: "Aceitou", para: "Recusada", condicao: "não" },
  ],
};
