import type { ProcessoBpmnEntrada } from "@repo/bpmn";

const POLITICA = "docs/compliance/soc2/policies/06-vendor-management-policy.md";
const DPA = "docs/compliance/dpa-fornecedores.md";

export const PZ_08: ProcessoBpmnEntrada = {
  codigo: "PZ-08",
  nome: "Revisão de risco e vendor",
  fonte: [
    {
      arquivo: POLITICA,
      secao:
        "§3 Vendor Risk Tiers; §4.1 New Vendor Onboarding; §5 Registry; §6 Contractual Requirements",
    },
    {
      arquivo: DPA,
      secao:
        "§0 Como ler (embutido, a assinar, não encontrado); §3 Ações consolidadas",
    },
  ],
  lacunas: [
    "A política se contradiz no tier 2: a tabela do §3 pede DPA + questionário (sem SOC 2), e o §4.1 pede relatório SOC 2 para tier 1 ou 2. O diagrama segue o §4.1.",
    "Quem faz a diligência (pedir SOC 2, DPA, questionário) não está nomeado; só quem aprova (Engineering Lead; CTO no tier 1). As raias usam cargos, e o RACI do playbook §4 está em branco.",
    "A política não diz o que acontece quando a revisão reprova, nem quem revisa os termos de um fornecedor tier 3 ou se ele entra no registro.",
    "O registro do §5 da política (Supabase, Railway, BetterStack, todos com DPA ✅) diverge do inventário de dpa-fornecedores.md (Neon, Sentry; seis DPAs 'a assinar' e quatro 'não encontrado'). O playbook §6 já aponta os dois documentos que discordam.",
    "Revisão anual (§4.2) e desligamento de fornecedor (§4.3) são ciclos próprios e não estão neste diagrama.",
    "A descrição do PZ-08 no mapa fala em 'matriz de risco por classe de dado'; a política classifica por tier, não por classe de dado.",
    "A política está em inglês, escrita para 'Cosmos', versão 1.0 de 2026-05-19.",
  ],
  pool: "Nebuloz — contratação de fornecedor",
  raias: [
    {
      id: "Raia_diligencia",
      nome: "Responsável pela diligência (não nomeado)",
    },
    { id: "Raia_eng", nome: "Engineering Lead" },
    { id: "Raia_cto", nome: "CTO" },
  ],
  nos: [
    {
      id: "Inicio",
      tipo: "inicio",
      nome: "Fornecedor novo a contratar",
      raia: "Raia_diligencia",
      origem: "política §4.1",
    },
    {
      id: "Classificar",
      tipo: "tarefaUsuario",
      nome: "Classificar tier (1 crítico, 2 significativo, 3 padrão)",
      raia: "Raia_diligencia",
      origem: "política §3",
    },
    {
      id: "QualTier",
      tipo: "gatewayExclusivo",
      nome: "Tier?",
      raia: "Raia_diligencia",
      origem: "política §3",
    },
    {
      id: "RevisarTermos",
      tipo: "tarefaUsuario",
      nome: "Revisar termos de serviço padrão",
      raia: "Raia_diligencia",
      origem: "política §3 Tier 3",
    },
    {
      id: "Tier3Liberado",
      tipo: "fim",
      nome: "Fornecedor tier 3 liberado",
      raia: "Raia_diligencia",
    },
    {
      id: "PedirSoc2",
      tipo: "tarefaUsuario",
      nome: "Pedir SOC 2 Tipo II (ou ISO 27001, CSA STAR)",
      raia: "Raia_diligencia",
      origem: "política §4.1 passo 1",
    },
    {
      id: "DadoPessoal",
      tipo: "gatewayExclusivo",
      nome: "Trata dado pessoal?",
      raia: "Raia_diligencia",
      origem: "política §4.1 passo 2",
    },
    {
      id: "ConferirDpa",
      tipo: "tarefaUsuario",
      nome: "Conferir DPA em fonte primária",
      raia: "Raia_diligencia",
      origem: "dpa-fornecedores §0",
    },
    {
      id: "SituacaoDpa",
      tipo: "gatewayExclusivo",
      nome: "Situação do DPA?",
      raia: "Raia_diligencia",
      origem: "dpa-fornecedores §0",
    },
    {
      id: "AssinarDpa",
      tipo: "tarefaUsuario",
      nome: "Aceitar no portal ou assinar a via",
      raia: "Raia_diligencia",
      origem: "dpa-fornecedores §0 'a assinar'",
    },
    {
      id: "PedirDpa",
      tipo: "tarefaUsuario",
      nome: "Pedir DPA ao fornecedor",
      raia: "Raia_diligencia",
      origem: "dpa-fornecedores §3",
    },
    {
      id: "JuntaDpa",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_diligencia",
    },
    {
      id: "Clausulas",
      tipo: "tarefaUsuario",
      nome: "Conferir cláusulas: incidente em 72 h, auditoria, deleção, subprocessador",
      raia: "Raia_diligencia",
      origem: "política §6",
    },
    {
      id: "Questionario",
      tipo: "tarefaUsuario",
      nome: "Aplicar questionário de segurança",
      raia: "Raia_diligencia",
      origem: "política §4.1 passo 3",
    },
    {
      id: "RevisaoEng",
      tipo: "tarefaUsuario",
      nome: "Revisar e aprovar",
      raia: "Raia_eng",
      origem: "política §4.1 passo 4",
    },
    {
      id: "AprovadoEng",
      tipo: "gatewayExclusivo",
      nome: "Aprovado?",
      raia: "Raia_eng",
    },
    {
      id: "EhTier1",
      tipo: "gatewayExclusivo",
      nome: "Tier 1?",
      raia: "Raia_eng",
      origem: "política §4.1 passo 5",
    },
    {
      id: "RevisaoCto",
      tipo: "tarefaUsuario",
      nome: "Aprovar fornecedor tier 1",
      raia: "Raia_cto",
      origem: "política §4.1 passo 5",
    },
    {
      id: "AprovadoCto",
      tipo: "gatewayExclusivo",
      nome: "Aprovado pelo CTO?",
      raia: "Raia_cto",
    },
    {
      id: "JuntaAprovado",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_eng",
    },
    {
      id: "Registrar",
      tipo: "tarefaUsuario",
      nome: "Registrar no inventário e confirmar o contrato no Charter",
      raia: "Raia_eng",
      origem: "política §5; dpa-fornecedores §0 (CharterVendor)",
    },
    {
      id: "Contratado",
      tipo: "fim",
      nome: "Fornecedor contratado",
      raia: "Raia_eng",
    },
    {
      id: "JuntaReprovado",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_cto",
    },
    {
      id: "NaoAprovado",
      tipo: "fim",
      nome: "Fornecedor não aprovado",
      raia: "Raia_cto",
    },
  ],
  fluxos: [
    { de: "Inicio", para: "Classificar" },
    { de: "Classificar", para: "QualTier" },
    { de: "QualTier", para: "RevisarTermos", condicao: "tier 3" },
    { de: "QualTier", para: "PedirSoc2", condicao: "tier 1 ou 2" },
    { de: "RevisarTermos", para: "Tier3Liberado" },
    { de: "PedirSoc2", para: "DadoPessoal" },
    { de: "DadoPessoal", para: "ConferirDpa", condicao: "sim" },
    { de: "DadoPessoal", para: "JuntaDpa", condicao: "não" },
    { de: "ConferirDpa", para: "SituacaoDpa" },
    { de: "SituacaoDpa", para: "JuntaDpa", condicao: "embutido" },
    { de: "SituacaoDpa", para: "AssinarDpa", condicao: "a assinar" },
    { de: "SituacaoDpa", para: "PedirDpa", condicao: "não encontrado" },
    { de: "AssinarDpa", para: "JuntaDpa" },
    { de: "PedirDpa", para: "JuntaDpa" },
    { de: "JuntaDpa", para: "Clausulas" },
    { de: "Clausulas", para: "Questionario" },
    { de: "Questionario", para: "RevisaoEng" },
    { de: "RevisaoEng", para: "AprovadoEng" },
    { de: "AprovadoEng", para: "EhTier1", condicao: "sim" },
    { de: "AprovadoEng", para: "JuntaReprovado", condicao: "não" },
    { de: "EhTier1", para: "RevisaoCto", condicao: "sim" },
    { de: "EhTier1", para: "JuntaAprovado", condicao: "não" },
    { de: "RevisaoCto", para: "AprovadoCto" },
    { de: "AprovadoCto", para: "JuntaAprovado", condicao: "sim" },
    { de: "AprovadoCto", para: "JuntaReprovado", condicao: "não" },
    { de: "JuntaAprovado", para: "Registrar" },
    { de: "Registrar", para: "Contratado" },
    { de: "JuntaReprovado", para: "NaoAprovado" },
  ],
};
