import type { ProcessoBpmnEntrada } from "@repo/bpmn";

const ACTION = "apps/backoffice/app/actions/provisioning.ts";
const TENANT = "packages/provisioning/src/tenant.ts";

export const PZ_10: ProcessoBpmnEntrada = {
  codigo: "PZ-10",
  nome: "Provisionamento de tenant",
  fonte: [
    { arquivo: ACTION, secao: "provisionTenantAction" },
    { arquivo: TENANT, secao: "provisionTenant (transação)" },
    {
      arquivo: "packages/provisioning/src/modules.ts",
      secao: "contractModule",
    },
    { arquivo: "packages/provisioning/src/slug.ts", secao: "uniqueSlug" },
    {
      arquivo: "apps/backoffice/lib/guard.ts",
      secao: "requirePlatformStaff, assertCanWrite",
    },
    {
      arquivo: "apps/backoffice/app/(staff)/clientes/novo/form.tsx",
      secao: "formulário e barreira de confirmação",
    },
    {
      arquivo: "apps/app/app/(unauthenticated)/invite/[token]/page.tsx",
      secao: "aceite do convite",
    },
    {
      arquivo: "docs/comercial/mapa-de-processo.md",
      secao: "§6 Provisionamento (gatilho manual)",
    },
  ],
  lacunas: [
    "Proposta ACEITA não dispara o provisionamento: é passo manual em /clientes/novo, sem vínculo de volta à proposta além de tenantProvisionadoSlug (mapa §6).",
    "O back-office não envia o convite. O dono sem conta aceita em /invite/<id> no app, mas como ele recebe esse link não está no código do provisionamento.",
    "O convite vale 14 dias; nada no fluxo trata expiração nem reenvio.",
    "O painel manda só módulo e status: assentos e expiresAt nascem nulos (provisionTenantAction), então 'renova em N dias' fica sem dado (PRODUCT.md, Lacunas).",
    "Falha dentro da transação (por exemplo, slug esgotado após 10 sufixos) desfaz tudo e volta como erro; não está desenhada como caminho próprio.",
    "Preparar Charter e Meridian (bootstrapCharterAction, bootstrapMeridianAction) é passo separado na tela do cliente, não encadeado ao provisionamento; ficou fora deste diagrama.",
    "A descrição do PZ-10 no mapa diz 'owner convidado'; o código só convida quando o e-mail ainda não tem conta — com conta, vincula direto como ADMIN.",
  ],
  pool: "Nebuloz — provisionamento de cliente",
  raias: [
    { id: "Raia_staff", nome: "Staff ADMIN" },
    { id: "Raia_backoffice", nome: "Back-office" },
    { id: "Raia_dono", nome: "Dono do cliente" },
  ],
  nos: [
    {
      id: "Inicio",
      tipo: "inicio",
      nome: "Decisão de criar o cliente (hoje: proposta aceita, à mão)",
      raia: "Raia_staff",
      origem: "mapa §6 Entrada",
    },
    {
      id: "Preencher",
      tipo: "tarefaUsuario",
      nome: "Preencher nome, e-mail do dono e módulos (ACTIVE ou TRIAL)",
      raia: "Raia_staff",
      origem: "clientes/novo/form.tsx",
    },
    {
      id: "Confirmar",
      tipo: "tarefaUsuario",
      nome: "Confirmar na barreira que nomeia alvo e consequência",
      raia: "Raia_staff",
      origem: "form.tsx ConfirmarAcao",
    },
    {
      id: "Guard",
      tipo: "tarefaServico",
      nome: "Guard: sessão, teto, equipe, 2FA, escrita e cota de provisionamento",
      raia: "Raia_backoffice",
      origem: "provisioning.ts:145-160; guard.ts",
    },
    {
      id: "Autorizado",
      tipo: "gatewayExclusivo",
      nome: "Autorizado?",
      raia: "Raia_backoffice",
      origem: "guard.ts StaffAuthError",
    },
    {
      id: "Recusado",
      tipo: "fim",
      nome: "Recusado, com o motivo na tela",
      raia: "Raia_backoffice",
      origem: "safe-action Result",
    },
    {
      id: "Slug",
      tipo: "tarefaServico",
      nome: "Gerar slug único (até 10 sufixos)",
      raia: "Raia_backoffice",
      origem: "slug.ts uniqueSlug",
    },
    {
      id: "CriarTenant",
      tipo: "tarefaServico",
      nome: "Criar tenant",
      raia: "Raia_backoffice",
      origem: "tenant.ts provisionTenant",
    },
    {
      id: "BuscarDono",
      tipo: "tarefaServico",
      nome: "Procurar conta pelo e-mail do dono",
      raia: "Raia_backoffice",
      origem: "tenant.ts",
    },
    {
      id: "DonoTemConta",
      tipo: "gatewayExclusivo",
      nome: "Dono já tem conta?",
      raia: "Raia_backoffice",
      origem: "tenant.ts",
    },
    {
      id: "Vincular",
      tipo: "tarefaServico",
      nome: "Vincular dono como ADMIN (TenantMember)",
      raia: "Raia_backoffice",
      origem: "tenant.ts",
    },
    {
      id: "Convidar",
      tipo: "tarefaServico",
      nome: "Criar convite ADMIN de 14 dias (TenantInvitation)",
      raia: "Raia_backoffice",
      origem: "tenant.ts INVITE_TTL_DAYS",
    },
    {
      id: "JuntaDono",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_backoffice",
    },
    {
      id: "Contratar",
      tipo: "tarefaServico",
      nome: "Contratar cada módulo: upsert, invalida cache, audita",
      raia: "Raia_backoffice",
      origem: "modules.ts contractModule",
    },
    {
      id: "Auditar",
      tipo: "tarefaServico",
      nome: "Auditar tenant.provisioned",
      raia: "Raia_backoffice",
      origem: "tenant.ts logPlatformAudit",
    },
    {
      id: "ConvitePendente",
      tipo: "gatewayExclusivo",
      nome: "Convite pendente?",
      raia: "Raia_backoffice",
      origem: "provisioning.ts ownerLinked",
    },
    {
      id: "NoAr",
      tipo: "fim",
      nome: "Cliente no ar com dono",
      raia: "Raia_backoffice",
    },
    {
      id: "Aceitar",
      tipo: "tarefaUsuario",
      nome: "Criar conta e aceitar o convite em /invite/<id>",
      raia: "Raia_dono",
      origem: "apps/app invite/[token]",
    },
    {
      id: "DonoEntra",
      tipo: "fim",
      nome: "Dono entra no cliente",
      raia: "Raia_dono",
    },
  ],
  fluxos: [
    { de: "Inicio", para: "Preencher" },
    { de: "Preencher", para: "Confirmar" },
    { de: "Confirmar", para: "Guard" },
    { de: "Guard", para: "Autorizado" },
    { de: "Autorizado", para: "Slug", condicao: "sim" },
    { de: "Autorizado", para: "Recusado", condicao: "não" },
    { de: "Slug", para: "CriarTenant" },
    { de: "CriarTenant", para: "BuscarDono" },
    { de: "BuscarDono", para: "DonoTemConta" },
    { de: "DonoTemConta", para: "Vincular", condicao: "sim" },
    { de: "DonoTemConta", para: "Convidar", condicao: "não" },
    { de: "Vincular", para: "JuntaDono" },
    { de: "Convidar", para: "JuntaDono" },
    { de: "JuntaDono", para: "Contratar" },
    { de: "Contratar", para: "Auditar" },
    { de: "Auditar", para: "ConvitePendente" },
    { de: "ConvitePendente", para: "NoAr", condicao: "não" },
    { de: "ConvitePendente", para: "Aceitar", condicao: "sim" },
    { de: "Aceitar", para: "DonoEntra" },
  ],
};
