import type { ProcessoBpmnEntrada } from "@repo/bpmn";

const PLANO = "docs/compliance/soc2/policies/02-incident-response-plan.md";

export const PZ_23: ProcessoBpmnEntrada = {
  codigo: "PZ-23",
  nome: "Resposta a incidente",
  fonte: [
    {
      arquivo: PLANO,
      secao:
        "§2 Severity; §3 Team; §4 Response Phases 1–6; §5 Evidence; §6 Customer Notification; §7 Regulatory Reporting",
    },
  ],
  lacunas: [
    "Quem detecta e faz o registro inicial (hora, fonte, canal, acionar o Incident Commander) não está nomeado; a raia diz isso.",
    "O plano não dá ordem entre notificação (§6, §7) e erradicação/recuperação (fases 4–5); o prazo de 72 h conta da descoberta, então o desenho põe a notificação logo após a contenção. Na prática correm em paralelo — o esquema só tem gateway exclusivo.",
    "P2/P3 manda 'monitorar escalada' sem gatilho de reclassificação; não há volta desenhada.",
    "Papéis por cargo (CTO, Engineering Lead, CEO, jurídico externo), sem nomes; o RACI do playbook §4 está em branco.",
    "O canal '#incident-AAAA-MM-DD-descricao' não diz em que ferramenta; o contato é security@nebuloz.ai, e a produção é nebuloz.ai — confirmar o domínio.",
    "BetterStack aparece como fonte de alerta, mas não consta do inventário de dpa-fornecedores.md (que tem Sentry).",
    "Os runbooks do §8 (conta comprometida, exfiltração, CVE) não estão desenhados; conta comprometida de staff segue PZ-22.",
    "O plano está em inglês, escrito para 'Cosmos', versão 1.0 de 2026-05-19.",
  ],
  pool: "Nebuloz — resposta a incidente de segurança",
  raias: [
    { id: "Raia_deteccao", nome: "Quem detecta (não nomeado)" },
    { id: "Raia_ic", nome: "Incident Commander (CTO)" },
    { id: "Raia_tecnico", nome: "Líder técnico (Engineering Lead)" },
    { id: "Raia_comunicacao", nome: "Comunicação (CEO) e jurídico" },
  ],
  nos: [
    {
      id: "Inicio",
      tipo: "inicio",
      nome: "Alerta, relato de usuário ou de terceiro",
      raia: "Raia_deteccao",
      origem: "§4 Fase 1 Triggers",
    },
    {
      id: "Registrar",
      tipo: "tarefaUsuario",
      nome: "Registrar hora e fonte, abrir canal, acionar o Incident Commander",
      raia: "Raia_deteccao",
      origem: "§4 Fase 1 Actions",
    },
    {
      id: "Triar",
      tipo: "tarefaUsuario",
      nome: "Triar em até 30 min: severidade P0–P3 e escopo",
      raia: "Raia_ic",
      origem: "§4 Fase 2; §2",
    },
    {
      id: "Notificar",
      tipo: "tarefaUsuario",
      nome: "Notificar o time e abrir a linha do tempo",
      raia: "Raia_ic",
      origem: "§4 Fase 2",
    },
    {
      id: "Severidade",
      tipo: "gatewayExclusivo",
      nome: "Severidade?",
      raia: "Raia_ic",
      origem: "§2",
    },
    {
      id: "Isolar",
      tipo: "tarefaUsuario",
      nome: "Isolar sistemas: chaves, sessões, IPs",
      raia: "Raia_tecnico",
      origem: "§4 Fase 3 P0/P1",
    },
    {
      id: "Preservar",
      tipo: "tarefaUsuario",
      nome: "Preservar evidência e ampliar logs",
      raia: "Raia_tecnico",
      origem: "§4 Fase 3; §5",
    },
    {
      id: "InformarCeo",
      tipo: "tarefaUsuario",
      nome: "Informar o CEO",
      raia: "Raia_comunicacao",
      origem: "§4 Fase 3 P0/P1",
    },
    {
      id: "Restringir",
      tipo: "tarefaUsuario",
      nome: "Restringir o componente e monitorar escalada",
      raia: "Raia_tecnico",
      origem: "§4 Fase 3 P2/P3",
    },
    {
      id: "JuntaContencao",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_ic",
    },
    {
      id: "NotificaCliente",
      tipo: "gatewayExclusivo",
      nome: "Cliente precisa ser notificado?",
      raia: "Raia_ic",
      origem: "§6",
    },
    {
      id: "AvisarClientes",
      tipo: "tarefaUsuario",
      nome: "Notificar clientes (P0: 72 h, com revisão jurídica)",
      raia: "Raia_comunicacao",
      origem: "§6",
    },
    {
      id: "StatusPage",
      tipo: "tarefaUsuario",
      nome: "Atualizar a status page",
      raia: "Raia_comunicacao",
      origem: "§6 P2/P3",
    },
    { id: "JuntaAviso", tipo: "gatewayExclusivo", nome: "", raia: "Raia_ic" },
    {
      id: "DadoPessoal",
      tipo: "gatewayExclusivo",
      nome: "Violação confirmada de dado pessoal?",
      raia: "Raia_ic",
      origem: "§7",
    },
    {
      id: "Anpd",
      tipo: "tarefaUsuario",
      nome: "Reportar à ANPD em 72 h (e GDPR se couber)",
      raia: "Raia_comunicacao",
      origem: "§7",
    },
    {
      id: "JuntaRegulador",
      tipo: "gatewayExclusivo",
      nome: "",
      raia: "Raia_ic",
    },
    {
      id: "Erradicar",
      tipo: "tarefaUsuario",
      nome: "Erradicar: causa raiz, correção, rotação de credenciais",
      raia: "Raia_tecnico",
      origem: "§4 Fase 4",
    },
    {
      id: "Recuperar",
      tipo: "tarefaUsuario",
      nome: "Recuperar: restaurar, verificar controles, monitorar 24 h",
      raia: "Raia_tecnico",
      origem: "§4 Fase 5",
    },
    {
      id: "PostMortem",
      tipo: "tarefaUsuario",
      nome: "Post-mortem sem culpa em até 5 dias úteis",
      raia: "Raia_ic",
      origem: "§4 Fase 6",
    },
    {
      id: "Atualizar",
      tipo: "tarefaUsuario",
      nome: "Atualizar runbooks e controles; compartilhar o resumo",
      raia: "Raia_ic",
      origem: "§4 Fase 6",
    },
    {
      id: "Encerrado",
      tipo: "fim",
      nome: "Incidente encerrado",
      raia: "Raia_ic",
    },
  ],
  fluxos: [
    { de: "Inicio", para: "Registrar" },
    { de: "Registrar", para: "Triar" },
    { de: "Triar", para: "Notificar" },
    { de: "Notificar", para: "Severidade" },
    { de: "Severidade", para: "Isolar", condicao: "P0 ou P1" },
    { de: "Severidade", para: "Restringir", condicao: "P2 ou P3" },
    { de: "Isolar", para: "Preservar" },
    { de: "Preservar", para: "InformarCeo" },
    { de: "InformarCeo", para: "JuntaContencao" },
    { de: "Restringir", para: "JuntaContencao" },
    { de: "JuntaContencao", para: "NotificaCliente" },
    {
      de: "NotificaCliente",
      para: "AvisarClientes",
      condicao: "sim: dado exposto ou impacto",
    },
    { de: "NotificaCliente", para: "StatusPage", condicao: "não" },
    { de: "AvisarClientes", para: "JuntaAviso" },
    { de: "StatusPage", para: "JuntaAviso" },
    { de: "JuntaAviso", para: "DadoPessoal" },
    { de: "DadoPessoal", para: "Anpd", condicao: "sim" },
    { de: "DadoPessoal", para: "JuntaRegulador", condicao: "não" },
    { de: "Anpd", para: "JuntaRegulador" },
    { de: "JuntaRegulador", para: "Erradicar" },
    { de: "Erradicar", para: "Recuperar" },
    { de: "Recuperar", para: "PostMortem" },
    { de: "PostMortem", para: "Atualizar" },
    { de: "Atualizar", para: "Encerrado" },
  ],
};
